class Hrefs():
    product = '/product'
    login = '/login'
    user = '/user'
    cart = '/cart'
    userFavorites = '/user/favorites'
    orders = '/orders'
    logout = '/logout'
    category = '/category'
    comment = '/comment'
    home = '/'
