class Hrefs():
    product = '/product'
    login = '/login'
    signup = '/signup'
    user = '/user'
    cart = '/cart'
    userFavorites = '/user/favorites'
    orders = '/orders'
    logout = '/logout'
    category = '/category'
    comment = '/comment'
    addComment = '/addcomment'
    home = '/'
    domain = 'https://www.reazon.ru'
    phones = '/phones'
    search = '/search'

    defaultProduct = '/43'
    defaultSearchQuery = '?q=iphone'
    cartDeliveryAnchor = '#delivery-info_cart'
    cartPaymentMethodAnchor = '#payment-method_cart'
