name: linter

on:
  pull_request:
    branches: [ main, base ]
  push:
    branches: [ main, base ]

jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install software
        run: sudo apt-get install -y chromium-browser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check code style
        run: make run-linter
